Repository iamwatchdogs/Stop_Watch_and_Countdown_Timer, pull requests merged in 2023-05, with the labels that each got.

#1 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#2 Whole Project
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  README.md
  index.html
  script.js
  src/OP.png
  src/stopwatch.png
  style.css
Labels: documentation, enhancement

#5 Bug fix
  script.js
Labels: bug
